---
name: "notify_show_userinfo"
pack: "freeipa"
description: "Rule firing on action_show_userinfo action completion"
enabled: true

trigger:
  type: "core.st2.generic.notifytrigger"
  parameters: {}

criteria:
  trigger.channel:
    pattern: "chatops"
    type: "equals"

action:
  ref: "chatops.post_message"
  parameters:
    message: "{{trigger.message}}"
