---
name: "rule_password_expiration"
pack: "freeipa"
description: "This rule checks the password effective days left"
enabled: true

trigger:
  type: "freeipa.password_expired_event"

criteria:
  trigger.password_daysleft:
    type: lessthan
    pattern: 8

action:
  ref: "freeipa.action_change_password"
  parameters:
    passw_daysleft: {{ "trigger.password_daysleft" }}

