---
name: "rule_webhook"
pack: "freeipa"
description: "Rule firing on when encounting webhooks"
enabled: true

trigger:
        type: "core.st2.webhook"
        parameters:
            url: "sample"

criteria:
  trigger.body.context.selected_option:
    type: "equals"
    pattern: "show_account_status"
    

action:
    ref: "freeipa.orquesta_show_userinfo"
    parameters:
      username: "{{trigger.body.user_name}}"
      channel: "{{trigger.body.channel_id}}"
