---
name: "rule_webhook_chg_password"
pack: "freeipa"
description: "Rule firing on when encounting webhooks that ask for changing password"
enabled: true

trigger:
        type: "core.st2.webhook"
        parameters:
            url: "sample"

criteria:
  trigger.body.context.selected_option:
    type: "equals"
    pattern: "change_password"
    

action:
    ref: "chatops.post_message"
    parameters:
      channel: "{{trigger.body.channel_id}}"
      message: |
        Please go to https://selfservice.sige.la/ to change your password.
        Thank you. :smile:
      extra:
        mattermost:
          pretext: |
            Hello, @{{trigger.body.user_name}}.

