---
name: "rule_webhook"
pack: "freeipa"
description: "Rule firing on when encounting webhooks that comes from show account info slash command from mattermost"
enabled: true

trigger:
        type: "core.st2.webhook"
        parameters:
            url: "sample"

criteria:
  trigger.body.token[0]:
    type: "equals"
    pattern: "6wpoukizff8d8grc9yasasb9jw"


action:
    ref: "freeipa.action_http_200"
    parameters:
      response_url: "{{trigger.body.response_url[0]}}"